spring:
  application:
    name: dubbo-demo-consumer
server:
  port: 8889
dubbo:
  application:
    name: ${spring.application.name}
    service-discovery:
      #使用应用级订阅服务
      migration: FORCE_APPLICATION
  # ??????
  registry:
    address: nacos://127.0.0.1:8848
    check: false
  # ???????????????????????????????????
  protocol:
    c
